#getAuthors
GET http://127.0.0.1:5000/authors

###
# getAuthorById  authors."updatedAt"

GET http://127.0.0.1:5000/authors/21

### 
# createAuthor
POST http://127.0.0.1:5000/authors HTTP/1.1
Content-Type: application/json

  {
    "full_name": "Ivan_Franko",
    "email": "1i-f@gmail.com",
    "nationality": "UA"
  }

### 
# updateAuthor
PUT http://127.0.0.1:5000/authors HTTP/1.1
Content-Type: application/json

  {
    "full_name": "Ivan Franko",
    "email": "ivfr@gmail.com",
    "nationality": "UA",
    "id": 24
  }

###
# deleteAuthor
DELETE http://127.0.0.1:5000/authors/22
