#getAuthors
GET http://127.0.0.1:5000/authors

###
# getAuthorById 

GET http://127.0.0.1:5000/authors/2

### 
# createAuthor
POST http://127.0.0.1:5000/authors HTTP/1.1
Content-Type: application/json

  {
    "full_name": "Ivan Franko",
    "email": "i-f@gmail.com",
    "nationality_id": "UA"
  }

### 
# updateAuthor
PUT http://127.0.0.1:5000/authors HTTP/1.1
Content-Type: application/json

  {
    "full_name": "Edgar_Allan_Poe",
    "email": "eap@gmail.com",
    "nationality_id": "UA",
    "id": 2
  }

###
# deleteAuthor
DELETE http://127.0.0.1:5000/authors/17