#getBooks
GET http://127.0.0.1:5000/books

###
# getBookById 

GET http://127.0.0.1:5000/books/4

### 
# createBook
POST http://127.0.0.1:5000/books HTTP/1.1
Content-Type: application/json

{
  "title": "Самый богатый человек в Вавилоне",
  "description": null,
  "genre": "Miphology",
  "shelf": "Shelf #6"
}

### 
# updateBook
PUT http://127.0.0.1:5000/books HTTP/1.1
Content-Type: application/json

 {
  "id": 25,
  "title": "Голодные Игры",
  "description": null,
  "genre": "Fantazy",
  "shelf": "Shelf #5"
}

###
# deleteBook
DELETE http://127.0.0.1:5000/books/25