#getCustomers
GET http://127.0.0.1:5000/customers

###
# getCustomerById 

GET http://127.0.0.1:5000/customers/3

### 
# createCustomer
POST http://127.0.0.1:5000/customers HTTP/1.1
Content-Type: application/json

{
  "title": "Самый богатый человек в Вавилоне",
  "description": null,
  "genre_id": "Miphology",
  "shelf_id": "Shelf #6"
}

### 
# updateCustomer
PUT http://127.0.0.1:5000/customers HTTP/1.1
Content-Type: application/json

 {
  "id": 35,
  "title": "Голодные игры",
  "description": null,
  "genre_id": "Fantazy",
  "shelf_id": "Shelf #6"
}

###
# deleteCustomer
DELETE http://127.0.0.1:5000/customers/32