#getCustomers
GET http://127.0.0.1:5000/customers

###
# getCustomerById 

GET http://127.0.0.1:5000/customers/1

### 
# createCustomer
POST http://127.0.0.1:5000/customers HTTP/1.1
Content-Type: application/json

{
    "full_name": "Will Smith",
    "email": "w-s@gmail.com",
    "phone": null, 
    "password": "password"
}

### 
# updateCustomer
PUT http://127.0.0.1:5000/customers HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "full_name": "Cavin McCalister",
    "email": "cmcc@gmail.com",
    "phone": 380660000000, 
    "password": "password"
}


###
# deleteCustomer
DELETE http://127.0.0.1:5000/customers/8